json2cbor: Initialize index before "for scope"
Observed issue on earlier version:

  json2cbor.c:157:5: error: for loop initial declarations are only allowed in C99 mode

Note, it's not mandatory for current master branch
since build script already sets the c99 flag,
but it won't cause any harm.

Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>